const turnStage = {
    describeSceneOne: 'DESCRIBE_SCENE_ONE',
    pickChallenge: 'PICK_CHALLENGE',
    prerollItems: 'PREROLL_ITEMS',
    storyBonus: 'STORY_BONUS',
    prerollAssist: 'PREROLL_ASSIST',
    challengeScene: 'CHALLENGE_SCENE',
    prerollAssistScene: 'PREROLL_ASSIST_SCENE',
    actionTokenOne: 'ACTION_TOKEN_ONE',  
    rolling: 'ROLLING',
    rollOne: 'ROLL_ONE',
    rollTwo: 'ROLL_TWO',
    evaluateOne: 'EVALUATE_ONE',
    postrollAssist: 'POSTROLL_ASSIST',
    postrollAssistScene: 'POSTROLL_ASSIST_SCENE',
    evaluateTwo: 'EVALUATE_TWO',
    describeSceneTwo: 'DESCRIBE_SCENE_TWO',
    kostcoBuy: 'KOSTCO_BUY',
    kostcoGive: 'KOSTCO_GIVE',
    kostcoDiscard: 'KOSTCO_DISCARD',
    actionTokenTwo: 'ACTION_TOKEN_TWO',
    passTurn: 'PASS_TURN',
    default: 'default',
}

export default turnStage